//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrisProxy.PlateInfo {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo")]
    public partial class RetryException : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo")]
    public partial class PlateInfoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime expiryDateField;
        
        private System.DateTime purchasedDateField;
        
        private string plateNumberField;
        
        private string regionNameField;
        
        private StatusType statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime expiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
                this.RaisePropertyChanged("expiryDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime purchasedDate {
            get {
                return this.purchasedDateField;
            }
            set {
                this.purchasedDateField = value;
                this.RaisePropertyChanged("purchasedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string plateNumber {
            get {
                return this.plateNumberField;
            }
            set {
                this.plateNumberField = value;
                this.RaisePropertyChanged("plateNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string regionName {
            get {
                return this.regionNameField;
            }
            set {
                this.regionNameField = value;
                this.RaisePropertyChanged("regionName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public StatusType status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo")]
    public enum StatusType {
        
        /// <remarks/>
        Valid,
        
        /// <remarks/>
        Expired,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.digitalpaytech.com/plateInfo")]
    public partial class InfoServiceFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string shortErrorMessageField;
        
        private string techImplementationDetailsField;
        
        private string errCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string shortErrorMessage {
            get {
                return this.shortErrorMessageField;
            }
            set {
                this.shortErrorMessageField = value;
                this.RaisePropertyChanged("shortErrorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string techImplementationDetails {
            get {
                return this.techImplementationDetailsField;
            }
            set {
                this.techImplementationDetailsField = value;
                this.RaisePropertyChanged("techImplementationDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string errCode {
            get {
                return this.errCodeField;
            }
            set {
                this.errCodeField = value;
                this.RaisePropertyChanged("errCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", ConfigurationName="PlateInfo.PlateInfoService")]
    public interface PlateInfoService {
        
        // CODEGEN: Generating message contract since the operation getUpdatedValidPlatesByGroup is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getUpdatedValidPlatesByGroup", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(IrisProxy.PlateInfo.RetryException), Action="http://ws.digitalpaytech.com/plateInfo/getUpdatedValidPlatesByGroup", Name="RetryException")]
        [System.ServiceModel.FaultContractAttribute(typeof(IrisProxy.PlateInfo.InfoServiceFault), Action="http://ws.digitalpaytech.com/plateInfo/getUpdatedValidPlatesByGroup", Name="InfoServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IrisProxy.PlateInfo.getUpdatedValidPlatesByGroupResponse getUpdatedValidPlatesByGroup(IrisProxy.PlateInfo.getUpdatedValidPlatesByGroup request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getUpdatedValidPlatesByGroup", ReplyAction="*")]
        System.Threading.Tasks.Task<IrisProxy.PlateInfo.getUpdatedValidPlatesByGroupResponse> getUpdatedValidPlatesByGroupAsync(IrisProxy.PlateInfo.getUpdatedValidPlatesByGroup request);
        
        // CODEGEN: Generating message contract since the operation getValidPlatesByGroup is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getValidPlatesByGroup", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(IrisProxy.PlateInfo.RetryException), Action="http://ws.digitalpaytech.com/plateInfo/getValidPlatesByGroup", Name="RetryException")]
        [System.ServiceModel.FaultContractAttribute(typeof(IrisProxy.PlateInfo.InfoServiceFault), Action="http://ws.digitalpaytech.com/plateInfo/getValidPlatesByGroup", Name="InfoServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IrisProxy.PlateInfo.getValidPlatesByGroupResponse getValidPlatesByGroup(IrisProxy.PlateInfo.getValidPlatesByGroup request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getValidPlatesByGroup", ReplyAction="*")]
        System.Threading.Tasks.Task<IrisProxy.PlateInfo.getValidPlatesByGroupResponse> getValidPlatesByGroupAsync(IrisProxy.PlateInfo.getValidPlatesByGroup request);
        
        // CODEGEN: Generating message contract since the operation getUpdatedValidPlates is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getUpdatedValidPlates", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(IrisProxy.PlateInfo.RetryException), Action="http://ws.digitalpaytech.com/plateInfo/getUpdatedValidPlates", Name="RetryException")]
        [System.ServiceModel.FaultContractAttribute(typeof(IrisProxy.PlateInfo.InfoServiceFault), Action="http://ws.digitalpaytech.com/plateInfo/getUpdatedValidPlates", Name="InfoServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IrisProxy.PlateInfo.getUpdatedValidPlatesResponse getUpdatedValidPlates(IrisProxy.PlateInfo.getUpdatedValidPlates request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getUpdatedValidPlates", ReplyAction="*")]
        System.Threading.Tasks.Task<IrisProxy.PlateInfo.getUpdatedValidPlatesResponse> getUpdatedValidPlatesAsync(IrisProxy.PlateInfo.getUpdatedValidPlates request);
        
        // CODEGEN: Generating message contract since the operation getPlateInfo is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getPlateInfo", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(IrisProxy.PlateInfo.RetryException), Action="http://ws.digitalpaytech.com/plateInfo/getPlateInfo", Name="RetryException")]
        [System.ServiceModel.FaultContractAttribute(typeof(IrisProxy.PlateInfo.InfoServiceFault), Action="http://ws.digitalpaytech.com/plateInfo/getPlateInfo", Name="InfoServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IrisProxy.PlateInfo.getPlateInfoResponse getPlateInfo(IrisProxy.PlateInfo.getPlateInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getPlateInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<IrisProxy.PlateInfo.getPlateInfoResponse> getPlateInfoAsync(IrisProxy.PlateInfo.getPlateInfo request);
        
        // CODEGEN: Generating message contract since the operation getValidPlatesByRegion is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getValidPlatesByRegion", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(IrisProxy.PlateInfo.RetryException), Action="http://ws.digitalpaytech.com/plateInfo/getValidPlatesByRegion", Name="RetryException")]
        [System.ServiceModel.FaultContractAttribute(typeof(IrisProxy.PlateInfo.InfoServiceFault), Action="http://ws.digitalpaytech.com/plateInfo/getValidPlatesByRegion", Name="InfoServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IrisProxy.PlateInfo.getValidPlatesByRegionResponse getValidPlatesByRegion(IrisProxy.PlateInfo.getValidPlatesByRegion request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getValidPlatesByRegion", ReplyAction="*")]
        System.Threading.Tasks.Task<IrisProxy.PlateInfo.getValidPlatesByRegionResponse> getValidPlatesByRegionAsync(IrisProxy.PlateInfo.getValidPlatesByRegion request);
        
        // CODEGEN: Generating message contract since the operation getGroups is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getGroups", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(IrisProxy.PlateInfo.RetryException), Action="http://ws.digitalpaytech.com/plateInfo/getGroups", Name="RetryException")]
        [System.ServiceModel.FaultContractAttribute(typeof(IrisProxy.PlateInfo.InfoServiceFault), Action="http://ws.digitalpaytech.com/plateInfo/getGroups", Name="InfoServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IrisProxy.PlateInfo.getGroupsResponse getGroups(IrisProxy.PlateInfo.getGroups request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getGroups", ReplyAction="*")]
        System.Threading.Tasks.Task<IrisProxy.PlateInfo.getGroupsResponse> getGroupsAsync(IrisProxy.PlateInfo.getGroups request);
        
        // CODEGEN: Generating message contract since the operation getExpiredPlatesByGroup is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getExpiredPlatesByGroup", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(IrisProxy.PlateInfo.RetryException), Action="http://ws.digitalpaytech.com/plateInfo/getExpiredPlatesByGroup", Name="RetryException")]
        [System.ServiceModel.FaultContractAttribute(typeof(IrisProxy.PlateInfo.InfoServiceFault), Action="http://ws.digitalpaytech.com/plateInfo/getExpiredPlatesByGroup", Name="InfoServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IrisProxy.PlateInfo.getExpiredPlatesByGroupResponse getExpiredPlatesByGroup(IrisProxy.PlateInfo.getExpiredPlatesByGroup request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getExpiredPlatesByGroup", ReplyAction="*")]
        System.Threading.Tasks.Task<IrisProxy.PlateInfo.getExpiredPlatesByGroupResponse> getExpiredPlatesByGroupAsync(IrisProxy.PlateInfo.getExpiredPlatesByGroup request);
        
        // CODEGEN: Generating message contract since the operation getExpiredPlatesByRegion is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getExpiredPlatesByRegion", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(IrisProxy.PlateInfo.RetryException), Action="http://ws.digitalpaytech.com/plateInfo/getExpiredPlatesByRegion", Name="RetryException")]
        [System.ServiceModel.FaultContractAttribute(typeof(IrisProxy.PlateInfo.InfoServiceFault), Action="http://ws.digitalpaytech.com/plateInfo/getExpiredPlatesByRegion", Name="InfoServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IrisProxy.PlateInfo.getExpiredPlatesByRegionResponse getExpiredPlatesByRegion(IrisProxy.PlateInfo.getExpiredPlatesByRegion request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getExpiredPlatesByRegion", ReplyAction="*")]
        System.Threading.Tasks.Task<IrisProxy.PlateInfo.getExpiredPlatesByRegionResponse> getExpiredPlatesByRegionAsync(IrisProxy.PlateInfo.getExpiredPlatesByRegion request);
        
        // CODEGEN: Generating message contract since the operation getRegions is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getRegions", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(IrisProxy.PlateInfo.RetryException), Action="http://ws.digitalpaytech.com/plateInfo/getRegions", Name="RetryException")]
        [System.ServiceModel.FaultContractAttribute(typeof(IrisProxy.PlateInfo.InfoServiceFault), Action="http://ws.digitalpaytech.com/plateInfo/getRegions", Name="InfoServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IrisProxy.PlateInfo.getRegionsResponse getRegions(IrisProxy.PlateInfo.getRegions request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getRegions", ReplyAction="*")]
        System.Threading.Tasks.Task<IrisProxy.PlateInfo.getRegionsResponse> getRegionsAsync(IrisProxy.PlateInfo.getRegions request);
        
        // CODEGEN: Generating message contract since the operation getValidPlates is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getValidPlates", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(IrisProxy.PlateInfo.RetryException), Action="http://ws.digitalpaytech.com/plateInfo/getValidPlates", Name="RetryException")]
        [System.ServiceModel.FaultContractAttribute(typeof(IrisProxy.PlateInfo.InfoServiceFault), Action="http://ws.digitalpaytech.com/plateInfo/getValidPlates", Name="InfoServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IrisProxy.PlateInfo.getValidPlatesResponse getValidPlates(IrisProxy.PlateInfo.getValidPlates request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getValidPlates", ReplyAction="*")]
        System.Threading.Tasks.Task<IrisProxy.PlateInfo.getValidPlatesResponse> getValidPlatesAsync(IrisProxy.PlateInfo.getValidPlates request);
        
        // CODEGEN: Generating message contract since the operation getUpdatedValidPlatesByRegion is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getUpdatedValidPlatesByRegion", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(IrisProxy.PlateInfo.RetryException), Action="http://ws.digitalpaytech.com/plateInfo/getUpdatedValidPlatesByRegion", Name="RetryException")]
        [System.ServiceModel.FaultContractAttribute(typeof(IrisProxy.PlateInfo.InfoServiceFault), Action="http://ws.digitalpaytech.com/plateInfo/getUpdatedValidPlatesByRegion", Name="InfoServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IrisProxy.PlateInfo.getUpdatedValidPlatesByRegionResponse getUpdatedValidPlatesByRegion(IrisProxy.PlateInfo.getUpdatedValidPlatesByRegion request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getUpdatedValidPlatesByRegion", ReplyAction="*")]
        System.Threading.Tasks.Task<IrisProxy.PlateInfo.getUpdatedValidPlatesByRegionResponse> getUpdatedValidPlatesByRegionAsync(IrisProxy.PlateInfo.getUpdatedValidPlatesByRegion request);
        
        // CODEGEN: Generating message contract since the operation getExpiredPlates is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getExpiredPlates", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(IrisProxy.PlateInfo.RetryException), Action="http://ws.digitalpaytech.com/plateInfo/getExpiredPlates", Name="RetryException")]
        [System.ServiceModel.FaultContractAttribute(typeof(IrisProxy.PlateInfo.InfoServiceFault), Action="http://ws.digitalpaytech.com/plateInfo/getExpiredPlates", Name="InfoServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IrisProxy.PlateInfo.getExpiredPlatesResponse getExpiredPlates(IrisProxy.PlateInfo.getExpiredPlates request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getExpiredPlates", ReplyAction="*")]
        System.Threading.Tasks.Task<IrisProxy.PlateInfo.getExpiredPlatesResponse> getExpiredPlatesAsync(IrisProxy.PlateInfo.getExpiredPlates request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.digitalpaytech.com/plateInfo")]
    public partial class UpdatedPlateInfoByGroupRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private string groupNameField;
        
        private System.DateTime lastCallDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string groupName {
            get {
                return this.groupNameField;
            }
            set {
                this.groupNameField = value;
                this.RaisePropertyChanged("groupName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime lastCallDate {
            get {
                return this.lastCallDateField;
            }
            set {
                this.lastCallDateField = value;
                this.RaisePropertyChanged("lastCallDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUpdatedValidPlatesByGroup {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        public IrisProxy.PlateInfo.UpdatedPlateInfoByGroupRequest UpdatedPlateInfoByGroupRequest;
        
        public getUpdatedValidPlatesByGroup() {
        }
        
        public getUpdatedValidPlatesByGroup(IrisProxy.PlateInfo.UpdatedPlateInfoByGroupRequest UpdatedPlateInfoByGroupRequest) {
            this.UpdatedPlateInfoByGroupRequest = UpdatedPlateInfoByGroupRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUpdatedValidPlatesByGroupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("plateInfos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IrisProxy.PlateInfo.PlateInfoType[] PlateInfoResponse;
        
        public getUpdatedValidPlatesByGroupResponse() {
        }
        
        public getUpdatedValidPlatesByGroupResponse(IrisProxy.PlateInfo.PlateInfoType[] PlateInfoResponse) {
            this.PlateInfoResponse = PlateInfoResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.digitalpaytech.com/plateInfo")]
    public partial class PlateInfoByGroupRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private string groupNameField;
        
        private int gracePeriodField;
        
        private bool gracePeriodFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string groupName {
            get {
                return this.groupNameField;
            }
            set {
                this.groupNameField = value;
                this.RaisePropertyChanged("groupName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int gracePeriod {
            get {
                return this.gracePeriodField;
            }
            set {
                this.gracePeriodField = value;
                this.RaisePropertyChanged("gracePeriod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gracePeriodSpecified {
            get {
                return this.gracePeriodFieldSpecified;
            }
            set {
                this.gracePeriodFieldSpecified = value;
                this.RaisePropertyChanged("gracePeriodSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getValidPlatesByGroup {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        public IrisProxy.PlateInfo.PlateInfoByGroupRequest PlateInfoByGroupRequest;
        
        public getValidPlatesByGroup() {
        }
        
        public getValidPlatesByGroup(IrisProxy.PlateInfo.PlateInfoByGroupRequest PlateInfoByGroupRequest) {
            this.PlateInfoByGroupRequest = PlateInfoByGroupRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getValidPlatesByGroupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("plateInfos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IrisProxy.PlateInfo.PlateInfoType[] PlateInfoResponse;
        
        public getValidPlatesByGroupResponse() {
        }
        
        public getValidPlatesByGroupResponse(IrisProxy.PlateInfo.PlateInfoType[] PlateInfoResponse) {
            this.PlateInfoResponse = PlateInfoResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.digitalpaytech.com/plateInfo")]
    public partial class UpdatedPlateInfoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private System.DateTime lastCallDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime lastCallDate {
            get {
                return this.lastCallDateField;
            }
            set {
                this.lastCallDateField = value;
                this.RaisePropertyChanged("lastCallDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUpdatedValidPlates {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        public IrisProxy.PlateInfo.UpdatedPlateInfoRequest UpdatedPlateInfoRequest;
        
        public getUpdatedValidPlates() {
        }
        
        public getUpdatedValidPlates(IrisProxy.PlateInfo.UpdatedPlateInfoRequest UpdatedPlateInfoRequest) {
            this.UpdatedPlateInfoRequest = UpdatedPlateInfoRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUpdatedValidPlatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("plateInfos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IrisProxy.PlateInfo.PlateInfoType[] PlateInfoResponse;
        
        public getUpdatedValidPlatesResponse() {
        }
        
        public getUpdatedValidPlatesResponse(IrisProxy.PlateInfo.PlateInfoType[] PlateInfoResponse) {
            this.PlateInfoResponse = PlateInfoResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.digitalpaytech.com/plateInfo")]
    public partial class PlateInfoByPlateRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private string plateNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string plateNumber {
            get {
                return this.plateNumberField;
            }
            set {
                this.plateNumberField = value;
                this.RaisePropertyChanged("plateNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.digitalpaytech.com/plateInfo")]
    public partial class PlateInfoByPlateResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PlateInfoType plateInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public PlateInfoType plateInfo {
            get {
                return this.plateInfoField;
            }
            set {
                this.plateInfoField = value;
                this.RaisePropertyChanged("plateInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPlateInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        public IrisProxy.PlateInfo.PlateInfoByPlateRequest PlateInfoByPlateRequest;
        
        public getPlateInfo() {
        }
        
        public getPlateInfo(IrisProxy.PlateInfo.PlateInfoByPlateRequest PlateInfoByPlateRequest) {
            this.PlateInfoByPlateRequest = PlateInfoByPlateRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPlateInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        public IrisProxy.PlateInfo.PlateInfoByPlateResponse PlateInfoByPlateResponse;
        
        public getPlateInfoResponse() {
        }
        
        public getPlateInfoResponse(IrisProxy.PlateInfo.PlateInfoByPlateResponse PlateInfoByPlateResponse) {
            this.PlateInfoByPlateResponse = PlateInfoByPlateResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.digitalpaytech.com/plateInfo")]
    public partial class PlateInfoByRegionRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private string regionField;
        
        private int gracePeriodField;
        
        private bool gracePeriodFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
                this.RaisePropertyChanged("region");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int gracePeriod {
            get {
                return this.gracePeriodField;
            }
            set {
                this.gracePeriodField = value;
                this.RaisePropertyChanged("gracePeriod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gracePeriodSpecified {
            get {
                return this.gracePeriodFieldSpecified;
            }
            set {
                this.gracePeriodFieldSpecified = value;
                this.RaisePropertyChanged("gracePeriodSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getValidPlatesByRegion {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        public IrisProxy.PlateInfo.PlateInfoByRegionRequest PlateInfoByRegionRequest;
        
        public getValidPlatesByRegion() {
        }
        
        public getValidPlatesByRegion(IrisProxy.PlateInfo.PlateInfoByRegionRequest PlateInfoByRegionRequest) {
            this.PlateInfoByRegionRequest = PlateInfoByRegionRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getValidPlatesByRegionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("plateInfos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IrisProxy.PlateInfo.PlateInfoType[] PlateInfoResponse;
        
        public getValidPlatesByRegionResponse() {
        }
        
        public getValidPlatesByRegionResponse(IrisProxy.PlateInfo.PlateInfoType[] PlateInfoResponse) {
            this.PlateInfoResponse = PlateInfoResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.digitalpaytech.com/plateInfo")]
    public partial class GroupRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo")]
    public partial class GroupType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string groupNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string groupName {
            get {
                return this.groupNameField;
            }
            set {
                this.groupNameField = value;
                this.RaisePropertyChanged("groupName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getGroups {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        public IrisProxy.PlateInfo.GroupRequest GroupRequest;
        
        public getGroups() {
        }
        
        public getGroups(IrisProxy.PlateInfo.GroupRequest GroupRequest) {
            this.GroupRequest = GroupRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getGroupsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("groups", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IrisProxy.PlateInfo.GroupType[] GroupResponse;
        
        public getGroupsResponse() {
        }
        
        public getGroupsResponse(IrisProxy.PlateInfo.GroupType[] GroupResponse) {
            this.GroupResponse = GroupResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.digitalpaytech.com/plateInfo")]
    public partial class ExpiredPlateInfoByGroupRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private string groupNameField;
        
        private int gracePeriodField;
        
        private bool gracePeriodFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string groupName {
            get {
                return this.groupNameField;
            }
            set {
                this.groupNameField = value;
                this.RaisePropertyChanged("groupName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int gracePeriod {
            get {
                return this.gracePeriodField;
            }
            set {
                this.gracePeriodField = value;
                this.RaisePropertyChanged("gracePeriod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gracePeriodSpecified {
            get {
                return this.gracePeriodFieldSpecified;
            }
            set {
                this.gracePeriodFieldSpecified = value;
                this.RaisePropertyChanged("gracePeriodSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getExpiredPlatesByGroup {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        public IrisProxy.PlateInfo.ExpiredPlateInfoByGroupRequest ExpiredPlateInfoByGroupRequest;
        
        public getExpiredPlatesByGroup() {
        }
        
        public getExpiredPlatesByGroup(IrisProxy.PlateInfo.ExpiredPlateInfoByGroupRequest ExpiredPlateInfoByGroupRequest) {
            this.ExpiredPlateInfoByGroupRequest = ExpiredPlateInfoByGroupRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getExpiredPlatesByGroupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("plateInfos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IrisProxy.PlateInfo.PlateInfoType[] PlateInfoResponse;
        
        public getExpiredPlatesByGroupResponse() {
        }
        
        public getExpiredPlatesByGroupResponse(IrisProxy.PlateInfo.PlateInfoType[] PlateInfoResponse) {
            this.PlateInfoResponse = PlateInfoResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.digitalpaytech.com/plateInfo")]
    public partial class ExpiredPlateInfoByRegionRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private string regionField;
        
        private int gracePeriodField;
        
        private bool gracePeriodFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
                this.RaisePropertyChanged("region");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int gracePeriod {
            get {
                return this.gracePeriodField;
            }
            set {
                this.gracePeriodField = value;
                this.RaisePropertyChanged("gracePeriod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gracePeriodSpecified {
            get {
                return this.gracePeriodFieldSpecified;
            }
            set {
                this.gracePeriodFieldSpecified = value;
                this.RaisePropertyChanged("gracePeriodSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getExpiredPlatesByRegion {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        public IrisProxy.PlateInfo.ExpiredPlateInfoByRegionRequest ExpiredPlateInfoByRegionRequest;
        
        public getExpiredPlatesByRegion() {
        }
        
        public getExpiredPlatesByRegion(IrisProxy.PlateInfo.ExpiredPlateInfoByRegionRequest ExpiredPlateInfoByRegionRequest) {
            this.ExpiredPlateInfoByRegionRequest = ExpiredPlateInfoByRegionRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getExpiredPlatesByRegionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("plateInfos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IrisProxy.PlateInfo.PlateInfoType[] PlateInfoResponse;
        
        public getExpiredPlatesByRegionResponse() {
        }
        
        public getExpiredPlatesByRegionResponse(IrisProxy.PlateInfo.PlateInfoType[] PlateInfoResponse) {
            this.PlateInfoResponse = PlateInfoResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.digitalpaytech.com/plateInfo")]
    public partial class RegionRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo")]
    public partial class RegionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string regionNameField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string regionName {
            get {
                return this.regionNameField;
            }
            set {
                this.regionNameField = value;
                this.RaisePropertyChanged("regionName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRegions {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        public IrisProxy.PlateInfo.RegionRequest RegionRequest;
        
        public getRegions() {
        }
        
        public getRegions(IrisProxy.PlateInfo.RegionRequest RegionRequest) {
            this.RegionRequest = RegionRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRegionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("regions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IrisProxy.PlateInfo.RegionType[] RegionResponse;
        
        public getRegionsResponse() {
        }
        
        public getRegionsResponse(IrisProxy.PlateInfo.RegionType[] RegionResponse) {
            this.RegionResponse = RegionResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.digitalpaytech.com/plateInfo")]
    public partial class PlateInfoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private int gracePeriodField;
        
        private bool gracePeriodFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int gracePeriod {
            get {
                return this.gracePeriodField;
            }
            set {
                this.gracePeriodField = value;
                this.RaisePropertyChanged("gracePeriod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gracePeriodSpecified {
            get {
                return this.gracePeriodFieldSpecified;
            }
            set {
                this.gracePeriodFieldSpecified = value;
                this.RaisePropertyChanged("gracePeriodSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getValidPlates {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        public IrisProxy.PlateInfo.PlateInfoRequest PlateInfoRequest;
        
        public getValidPlates() {
        }
        
        public getValidPlates(IrisProxy.PlateInfo.PlateInfoRequest PlateInfoRequest) {
            this.PlateInfoRequest = PlateInfoRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getValidPlatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("plateInfos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IrisProxy.PlateInfo.PlateInfoType[] PlateInfoResponse;
        
        public getValidPlatesResponse() {
        }
        
        public getValidPlatesResponse(IrisProxy.PlateInfo.PlateInfoType[] PlateInfoResponse) {
            this.PlateInfoResponse = PlateInfoResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.digitalpaytech.com/plateInfo")]
    public partial class UpdatedPlateInfoByRegionRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private string regionField;
        
        private System.DateTime lastCallDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
                this.RaisePropertyChanged("region");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime lastCallDate {
            get {
                return this.lastCallDateField;
            }
            set {
                this.lastCallDateField = value;
                this.RaisePropertyChanged("lastCallDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUpdatedValidPlatesByRegion {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        public IrisProxy.PlateInfo.UpdatedPlateInfoByRegionRequest UpdatedPlateInfoByRegionRequest;
        
        public getUpdatedValidPlatesByRegion() {
        }
        
        public getUpdatedValidPlatesByRegion(IrisProxy.PlateInfo.UpdatedPlateInfoByRegionRequest UpdatedPlateInfoByRegionRequest) {
            this.UpdatedPlateInfoByRegionRequest = UpdatedPlateInfoByRegionRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUpdatedValidPlatesByRegionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("plateInfos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IrisProxy.PlateInfo.PlateInfoType[] PlateInfoResponse;
        
        public getUpdatedValidPlatesByRegionResponse() {
        }
        
        public getUpdatedValidPlatesByRegionResponse(IrisProxy.PlateInfo.PlateInfoType[] PlateInfoResponse) {
            this.PlateInfoResponse = PlateInfoResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.digitalpaytech.com/plateInfo")]
    public partial class ExpiredPlateInfoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private int gracePeriodField;
        
        private bool gracePeriodFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int gracePeriod {
            get {
                return this.gracePeriodField;
            }
            set {
                this.gracePeriodField = value;
                this.RaisePropertyChanged("gracePeriod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gracePeriodSpecified {
            get {
                return this.gracePeriodFieldSpecified;
            }
            set {
                this.gracePeriodFieldSpecified = value;
                this.RaisePropertyChanged("gracePeriodSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getExpiredPlates {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        public IrisProxy.PlateInfo.ExpiredPlateInfoRequest ExpiredPlateInfoRequest;
        
        public getExpiredPlates() {
        }
        
        public getExpiredPlates(IrisProxy.PlateInfo.ExpiredPlateInfoRequest ExpiredPlateInfoRequest) {
            this.ExpiredPlateInfoRequest = ExpiredPlateInfoRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getExpiredPlatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("plateInfos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IrisProxy.PlateInfo.PlateInfoType[] PlateInfoResponse;
        
        public getExpiredPlatesResponse() {
        }
        
        public getExpiredPlatesResponse(IrisProxy.PlateInfo.PlateInfoType[] PlateInfoResponse) {
            this.PlateInfoResponse = PlateInfoResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PlateInfoServiceChannel : IrisProxy.PlateInfo.PlateInfoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlateInfoServiceClient : System.ServiceModel.ClientBase<IrisProxy.PlateInfo.PlateInfoService>, IrisProxy.PlateInfo.PlateInfoService {
        
        public PlateInfoServiceClient() {
        }
        
        public PlateInfoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlateInfoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlateInfoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlateInfoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IrisProxy.PlateInfo.getUpdatedValidPlatesByGroupResponse IrisProxy.PlateInfo.PlateInfoService.getUpdatedValidPlatesByGroup(IrisProxy.PlateInfo.getUpdatedValidPlatesByGroup request) {
            return base.Channel.getUpdatedValidPlatesByGroup(request);
        }
        
        public IrisProxy.PlateInfo.PlateInfoType[] getUpdatedValidPlatesByGroup(IrisProxy.PlateInfo.UpdatedPlateInfoByGroupRequest UpdatedPlateInfoByGroupRequest) {
            IrisProxy.PlateInfo.getUpdatedValidPlatesByGroup inValue = new IrisProxy.PlateInfo.getUpdatedValidPlatesByGroup();
            inValue.UpdatedPlateInfoByGroupRequest = UpdatedPlateInfoByGroupRequest;
            IrisProxy.PlateInfo.getUpdatedValidPlatesByGroupResponse retVal = ((IrisProxy.PlateInfo.PlateInfoService)(this)).getUpdatedValidPlatesByGroup(inValue);
            return retVal.PlateInfoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IrisProxy.PlateInfo.getUpdatedValidPlatesByGroupResponse> IrisProxy.PlateInfo.PlateInfoService.getUpdatedValidPlatesByGroupAsync(IrisProxy.PlateInfo.getUpdatedValidPlatesByGroup request) {
            return base.Channel.getUpdatedValidPlatesByGroupAsync(request);
        }
        
        public System.Threading.Tasks.Task<IrisProxy.PlateInfo.getUpdatedValidPlatesByGroupResponse> getUpdatedValidPlatesByGroupAsync(IrisProxy.PlateInfo.UpdatedPlateInfoByGroupRequest UpdatedPlateInfoByGroupRequest) {
            IrisProxy.PlateInfo.getUpdatedValidPlatesByGroup inValue = new IrisProxy.PlateInfo.getUpdatedValidPlatesByGroup();
            inValue.UpdatedPlateInfoByGroupRequest = UpdatedPlateInfoByGroupRequest;
            return ((IrisProxy.PlateInfo.PlateInfoService)(this)).getUpdatedValidPlatesByGroupAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IrisProxy.PlateInfo.getValidPlatesByGroupResponse IrisProxy.PlateInfo.PlateInfoService.getValidPlatesByGroup(IrisProxy.PlateInfo.getValidPlatesByGroup request) {
            return base.Channel.getValidPlatesByGroup(request);
        }
        
        public IrisProxy.PlateInfo.PlateInfoType[] getValidPlatesByGroup(IrisProxy.PlateInfo.PlateInfoByGroupRequest PlateInfoByGroupRequest) {
            IrisProxy.PlateInfo.getValidPlatesByGroup inValue = new IrisProxy.PlateInfo.getValidPlatesByGroup();
            inValue.PlateInfoByGroupRequest = PlateInfoByGroupRequest;
            IrisProxy.PlateInfo.getValidPlatesByGroupResponse retVal = ((IrisProxy.PlateInfo.PlateInfoService)(this)).getValidPlatesByGroup(inValue);
            return retVal.PlateInfoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IrisProxy.PlateInfo.getValidPlatesByGroupResponse> IrisProxy.PlateInfo.PlateInfoService.getValidPlatesByGroupAsync(IrisProxy.PlateInfo.getValidPlatesByGroup request) {
            return base.Channel.getValidPlatesByGroupAsync(request);
        }
        
        public System.Threading.Tasks.Task<IrisProxy.PlateInfo.getValidPlatesByGroupResponse> getValidPlatesByGroupAsync(IrisProxy.PlateInfo.PlateInfoByGroupRequest PlateInfoByGroupRequest) {
            IrisProxy.PlateInfo.getValidPlatesByGroup inValue = new IrisProxy.PlateInfo.getValidPlatesByGroup();
            inValue.PlateInfoByGroupRequest = PlateInfoByGroupRequest;
            return ((IrisProxy.PlateInfo.PlateInfoService)(this)).getValidPlatesByGroupAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IrisProxy.PlateInfo.getUpdatedValidPlatesResponse IrisProxy.PlateInfo.PlateInfoService.getUpdatedValidPlates(IrisProxy.PlateInfo.getUpdatedValidPlates request) {
            return base.Channel.getUpdatedValidPlates(request);
        }
        
        public IrisProxy.PlateInfo.PlateInfoType[] getUpdatedValidPlates(IrisProxy.PlateInfo.UpdatedPlateInfoRequest UpdatedPlateInfoRequest) {
            IrisProxy.PlateInfo.getUpdatedValidPlates inValue = new IrisProxy.PlateInfo.getUpdatedValidPlates();
            inValue.UpdatedPlateInfoRequest = UpdatedPlateInfoRequest;
            IrisProxy.PlateInfo.getUpdatedValidPlatesResponse retVal = ((IrisProxy.PlateInfo.PlateInfoService)(this)).getUpdatedValidPlates(inValue);
            return retVal.PlateInfoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IrisProxy.PlateInfo.getUpdatedValidPlatesResponse> IrisProxy.PlateInfo.PlateInfoService.getUpdatedValidPlatesAsync(IrisProxy.PlateInfo.getUpdatedValidPlates request) {
            return base.Channel.getUpdatedValidPlatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<IrisProxy.PlateInfo.getUpdatedValidPlatesResponse> getUpdatedValidPlatesAsync(IrisProxy.PlateInfo.UpdatedPlateInfoRequest UpdatedPlateInfoRequest) {
            IrisProxy.PlateInfo.getUpdatedValidPlates inValue = new IrisProxy.PlateInfo.getUpdatedValidPlates();
            inValue.UpdatedPlateInfoRequest = UpdatedPlateInfoRequest;
            return ((IrisProxy.PlateInfo.PlateInfoService)(this)).getUpdatedValidPlatesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IrisProxy.PlateInfo.getPlateInfoResponse IrisProxy.PlateInfo.PlateInfoService.getPlateInfo(IrisProxy.PlateInfo.getPlateInfo request) {
            return base.Channel.getPlateInfo(request);
        }
        
        public IrisProxy.PlateInfo.PlateInfoByPlateResponse getPlateInfo(IrisProxy.PlateInfo.PlateInfoByPlateRequest PlateInfoByPlateRequest) {
            IrisProxy.PlateInfo.getPlateInfo inValue = new IrisProxy.PlateInfo.getPlateInfo();
            inValue.PlateInfoByPlateRequest = PlateInfoByPlateRequest;
            IrisProxy.PlateInfo.getPlateInfoResponse retVal = ((IrisProxy.PlateInfo.PlateInfoService)(this)).getPlateInfo(inValue);
            return retVal.PlateInfoByPlateResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IrisProxy.PlateInfo.getPlateInfoResponse> IrisProxy.PlateInfo.PlateInfoService.getPlateInfoAsync(IrisProxy.PlateInfo.getPlateInfo request) {
            return base.Channel.getPlateInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<IrisProxy.PlateInfo.getPlateInfoResponse> getPlateInfoAsync(IrisProxy.PlateInfo.PlateInfoByPlateRequest PlateInfoByPlateRequest) {
            IrisProxy.PlateInfo.getPlateInfo inValue = new IrisProxy.PlateInfo.getPlateInfo();
            inValue.PlateInfoByPlateRequest = PlateInfoByPlateRequest;
            return ((IrisProxy.PlateInfo.PlateInfoService)(this)).getPlateInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IrisProxy.PlateInfo.getValidPlatesByRegionResponse IrisProxy.PlateInfo.PlateInfoService.getValidPlatesByRegion(IrisProxy.PlateInfo.getValidPlatesByRegion request) {
            return base.Channel.getValidPlatesByRegion(request);
        }
        
        public IrisProxy.PlateInfo.PlateInfoType[] getValidPlatesByRegion(IrisProxy.PlateInfo.PlateInfoByRegionRequest PlateInfoByRegionRequest) {
            IrisProxy.PlateInfo.getValidPlatesByRegion inValue = new IrisProxy.PlateInfo.getValidPlatesByRegion();
            inValue.PlateInfoByRegionRequest = PlateInfoByRegionRequest;
            IrisProxy.PlateInfo.getValidPlatesByRegionResponse retVal = ((IrisProxy.PlateInfo.PlateInfoService)(this)).getValidPlatesByRegion(inValue);
            return retVal.PlateInfoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IrisProxy.PlateInfo.getValidPlatesByRegionResponse> IrisProxy.PlateInfo.PlateInfoService.getValidPlatesByRegionAsync(IrisProxy.PlateInfo.getValidPlatesByRegion request) {
            return base.Channel.getValidPlatesByRegionAsync(request);
        }
        
        public System.Threading.Tasks.Task<IrisProxy.PlateInfo.getValidPlatesByRegionResponse> getValidPlatesByRegionAsync(IrisProxy.PlateInfo.PlateInfoByRegionRequest PlateInfoByRegionRequest) {
            IrisProxy.PlateInfo.getValidPlatesByRegion inValue = new IrisProxy.PlateInfo.getValidPlatesByRegion();
            inValue.PlateInfoByRegionRequest = PlateInfoByRegionRequest;
            return ((IrisProxy.PlateInfo.PlateInfoService)(this)).getValidPlatesByRegionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IrisProxy.PlateInfo.getGroupsResponse IrisProxy.PlateInfo.PlateInfoService.getGroups(IrisProxy.PlateInfo.getGroups request) {
            return base.Channel.getGroups(request);
        }
        
        public IrisProxy.PlateInfo.GroupType[] getGroups(IrisProxy.PlateInfo.GroupRequest GroupRequest) {
            IrisProxy.PlateInfo.getGroups inValue = new IrisProxy.PlateInfo.getGroups();
            inValue.GroupRequest = GroupRequest;
            IrisProxy.PlateInfo.getGroupsResponse retVal = ((IrisProxy.PlateInfo.PlateInfoService)(this)).getGroups(inValue);
            return retVal.GroupResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IrisProxy.PlateInfo.getGroupsResponse> IrisProxy.PlateInfo.PlateInfoService.getGroupsAsync(IrisProxy.PlateInfo.getGroups request) {
            return base.Channel.getGroupsAsync(request);
        }
        
        public System.Threading.Tasks.Task<IrisProxy.PlateInfo.getGroupsResponse> getGroupsAsync(IrisProxy.PlateInfo.GroupRequest GroupRequest) {
            IrisProxy.PlateInfo.getGroups inValue = new IrisProxy.PlateInfo.getGroups();
            inValue.GroupRequest = GroupRequest;
            return ((IrisProxy.PlateInfo.PlateInfoService)(this)).getGroupsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IrisProxy.PlateInfo.getExpiredPlatesByGroupResponse IrisProxy.PlateInfo.PlateInfoService.getExpiredPlatesByGroup(IrisProxy.PlateInfo.getExpiredPlatesByGroup request) {
            return base.Channel.getExpiredPlatesByGroup(request);
        }
        
        public IrisProxy.PlateInfo.PlateInfoType[] getExpiredPlatesByGroup(IrisProxy.PlateInfo.ExpiredPlateInfoByGroupRequest ExpiredPlateInfoByGroupRequest) {
            IrisProxy.PlateInfo.getExpiredPlatesByGroup inValue = new IrisProxy.PlateInfo.getExpiredPlatesByGroup();
            inValue.ExpiredPlateInfoByGroupRequest = ExpiredPlateInfoByGroupRequest;
            IrisProxy.PlateInfo.getExpiredPlatesByGroupResponse retVal = ((IrisProxy.PlateInfo.PlateInfoService)(this)).getExpiredPlatesByGroup(inValue);
            return retVal.PlateInfoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IrisProxy.PlateInfo.getExpiredPlatesByGroupResponse> IrisProxy.PlateInfo.PlateInfoService.getExpiredPlatesByGroupAsync(IrisProxy.PlateInfo.getExpiredPlatesByGroup request) {
            return base.Channel.getExpiredPlatesByGroupAsync(request);
        }
        
        public System.Threading.Tasks.Task<IrisProxy.PlateInfo.getExpiredPlatesByGroupResponse> getExpiredPlatesByGroupAsync(IrisProxy.PlateInfo.ExpiredPlateInfoByGroupRequest ExpiredPlateInfoByGroupRequest) {
            IrisProxy.PlateInfo.getExpiredPlatesByGroup inValue = new IrisProxy.PlateInfo.getExpiredPlatesByGroup();
            inValue.ExpiredPlateInfoByGroupRequest = ExpiredPlateInfoByGroupRequest;
            return ((IrisProxy.PlateInfo.PlateInfoService)(this)).getExpiredPlatesByGroupAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IrisProxy.PlateInfo.getExpiredPlatesByRegionResponse IrisProxy.PlateInfo.PlateInfoService.getExpiredPlatesByRegion(IrisProxy.PlateInfo.getExpiredPlatesByRegion request) {
            return base.Channel.getExpiredPlatesByRegion(request);
        }
        
        public IrisProxy.PlateInfo.PlateInfoType[] getExpiredPlatesByRegion(IrisProxy.PlateInfo.ExpiredPlateInfoByRegionRequest ExpiredPlateInfoByRegionRequest) {
            IrisProxy.PlateInfo.getExpiredPlatesByRegion inValue = new IrisProxy.PlateInfo.getExpiredPlatesByRegion();
            inValue.ExpiredPlateInfoByRegionRequest = ExpiredPlateInfoByRegionRequest;
            IrisProxy.PlateInfo.getExpiredPlatesByRegionResponse retVal = ((IrisProxy.PlateInfo.PlateInfoService)(this)).getExpiredPlatesByRegion(inValue);
            return retVal.PlateInfoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IrisProxy.PlateInfo.getExpiredPlatesByRegionResponse> IrisProxy.PlateInfo.PlateInfoService.getExpiredPlatesByRegionAsync(IrisProxy.PlateInfo.getExpiredPlatesByRegion request) {
            return base.Channel.getExpiredPlatesByRegionAsync(request);
        }
        
        public System.Threading.Tasks.Task<IrisProxy.PlateInfo.getExpiredPlatesByRegionResponse> getExpiredPlatesByRegionAsync(IrisProxy.PlateInfo.ExpiredPlateInfoByRegionRequest ExpiredPlateInfoByRegionRequest) {
            IrisProxy.PlateInfo.getExpiredPlatesByRegion inValue = new IrisProxy.PlateInfo.getExpiredPlatesByRegion();
            inValue.ExpiredPlateInfoByRegionRequest = ExpiredPlateInfoByRegionRequest;
            return ((IrisProxy.PlateInfo.PlateInfoService)(this)).getExpiredPlatesByRegionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IrisProxy.PlateInfo.getRegionsResponse IrisProxy.PlateInfo.PlateInfoService.getRegions(IrisProxy.PlateInfo.getRegions request) {
            return base.Channel.getRegions(request);
        }
        
        public IrisProxy.PlateInfo.RegionType[] getRegions(IrisProxy.PlateInfo.RegionRequest RegionRequest) {
            IrisProxy.PlateInfo.getRegions inValue = new IrisProxy.PlateInfo.getRegions();
            inValue.RegionRequest = RegionRequest;
            IrisProxy.PlateInfo.getRegionsResponse retVal = ((IrisProxy.PlateInfo.PlateInfoService)(this)).getRegions(inValue);
            return retVal.RegionResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IrisProxy.PlateInfo.getRegionsResponse> IrisProxy.PlateInfo.PlateInfoService.getRegionsAsync(IrisProxy.PlateInfo.getRegions request) {
            return base.Channel.getRegionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<IrisProxy.PlateInfo.getRegionsResponse> getRegionsAsync(IrisProxy.PlateInfo.RegionRequest RegionRequest) {
            IrisProxy.PlateInfo.getRegions inValue = new IrisProxy.PlateInfo.getRegions();
            inValue.RegionRequest = RegionRequest;
            return ((IrisProxy.PlateInfo.PlateInfoService)(this)).getRegionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IrisProxy.PlateInfo.getValidPlatesResponse IrisProxy.PlateInfo.PlateInfoService.getValidPlates(IrisProxy.PlateInfo.getValidPlates request) {
            return base.Channel.getValidPlates(request);
        }
        
        public IrisProxy.PlateInfo.PlateInfoType[] getValidPlates(IrisProxy.PlateInfo.PlateInfoRequest PlateInfoRequest) {
            IrisProxy.PlateInfo.getValidPlates inValue = new IrisProxy.PlateInfo.getValidPlates();
            inValue.PlateInfoRequest = PlateInfoRequest;
            IrisProxy.PlateInfo.getValidPlatesResponse retVal = ((IrisProxy.PlateInfo.PlateInfoService)(this)).getValidPlates(inValue);
            return retVal.PlateInfoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IrisProxy.PlateInfo.getValidPlatesResponse> IrisProxy.PlateInfo.PlateInfoService.getValidPlatesAsync(IrisProxy.PlateInfo.getValidPlates request) {
            return base.Channel.getValidPlatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<IrisProxy.PlateInfo.getValidPlatesResponse> getValidPlatesAsync(IrisProxy.PlateInfo.PlateInfoRequest PlateInfoRequest) {
            IrisProxy.PlateInfo.getValidPlates inValue = new IrisProxy.PlateInfo.getValidPlates();
            inValue.PlateInfoRequest = PlateInfoRequest;
            return ((IrisProxy.PlateInfo.PlateInfoService)(this)).getValidPlatesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IrisProxy.PlateInfo.getUpdatedValidPlatesByRegionResponse IrisProxy.PlateInfo.PlateInfoService.getUpdatedValidPlatesByRegion(IrisProxy.PlateInfo.getUpdatedValidPlatesByRegion request) {
            return base.Channel.getUpdatedValidPlatesByRegion(request);
        }
        
        public IrisProxy.PlateInfo.PlateInfoType[] getUpdatedValidPlatesByRegion(IrisProxy.PlateInfo.UpdatedPlateInfoByRegionRequest UpdatedPlateInfoByRegionRequest) {
            IrisProxy.PlateInfo.getUpdatedValidPlatesByRegion inValue = new IrisProxy.PlateInfo.getUpdatedValidPlatesByRegion();
            inValue.UpdatedPlateInfoByRegionRequest = UpdatedPlateInfoByRegionRequest;
            IrisProxy.PlateInfo.getUpdatedValidPlatesByRegionResponse retVal = ((IrisProxy.PlateInfo.PlateInfoService)(this)).getUpdatedValidPlatesByRegion(inValue);
            return retVal.PlateInfoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IrisProxy.PlateInfo.getUpdatedValidPlatesByRegionResponse> IrisProxy.PlateInfo.PlateInfoService.getUpdatedValidPlatesByRegionAsync(IrisProxy.PlateInfo.getUpdatedValidPlatesByRegion request) {
            return base.Channel.getUpdatedValidPlatesByRegionAsync(request);
        }
        
        public System.Threading.Tasks.Task<IrisProxy.PlateInfo.getUpdatedValidPlatesByRegionResponse> getUpdatedValidPlatesByRegionAsync(IrisProxy.PlateInfo.UpdatedPlateInfoByRegionRequest UpdatedPlateInfoByRegionRequest) {
            IrisProxy.PlateInfo.getUpdatedValidPlatesByRegion inValue = new IrisProxy.PlateInfo.getUpdatedValidPlatesByRegion();
            inValue.UpdatedPlateInfoByRegionRequest = UpdatedPlateInfoByRegionRequest;
            return ((IrisProxy.PlateInfo.PlateInfoService)(this)).getUpdatedValidPlatesByRegionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IrisProxy.PlateInfo.getExpiredPlatesResponse IrisProxy.PlateInfo.PlateInfoService.getExpiredPlates(IrisProxy.PlateInfo.getExpiredPlates request) {
            return base.Channel.getExpiredPlates(request);
        }
        
        public IrisProxy.PlateInfo.PlateInfoType[] getExpiredPlates(IrisProxy.PlateInfo.ExpiredPlateInfoRequest ExpiredPlateInfoRequest) {
            IrisProxy.PlateInfo.getExpiredPlates inValue = new IrisProxy.PlateInfo.getExpiredPlates();
            inValue.ExpiredPlateInfoRequest = ExpiredPlateInfoRequest;
            IrisProxy.PlateInfo.getExpiredPlatesResponse retVal = ((IrisProxy.PlateInfo.PlateInfoService)(this)).getExpiredPlates(inValue);
            return retVal.PlateInfoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IrisProxy.PlateInfo.getExpiredPlatesResponse> IrisProxy.PlateInfo.PlateInfoService.getExpiredPlatesAsync(IrisProxy.PlateInfo.getExpiredPlates request) {
            return base.Channel.getExpiredPlatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<IrisProxy.PlateInfo.getExpiredPlatesResponse> getExpiredPlatesAsync(IrisProxy.PlateInfo.ExpiredPlateInfoRequest ExpiredPlateInfoRequest) {
            IrisProxy.PlateInfo.getExpiredPlates inValue = new IrisProxy.PlateInfo.getExpiredPlates();
            inValue.ExpiredPlateInfoRequest = ExpiredPlateInfoRequest;
            return ((IrisProxy.PlateInfo.PlateInfoService)(this)).getExpiredPlatesAsync(inValue);
        }
    }
}
